[package]
name = "dodge_the_creeps"
version = "0.1.0"
authors = ["Breno Viana <bmfviana@gmail.com>"]
edition = "2018"

[dependencies]
gdnative = "0.9.0-preview.0"
rand = "0.7.3"

[lib]
crate-type = ["cdylib"]
